---
formula:
  ack:
  act:
  ansible:
  aom:
  archey4:
  aribb24:
  artillery:
  asdf:
  atac:
  awscli:
  axel:
  bash:
  bash-completion:
  bat:
  binwalk:
  brotli:
  btop:
  bun:
  c-ares:
  ca-certificates:
  caddy:
  cairo:
  capstone:
  certifi:
  cffi:
  cjson:
  colima:
  commitizen:
  coreutils:
  cowsay:
  cryptography:
  curl:
  dav1d:
  ddrescue:
  deno:
  docker:
  docker-buildx:
  docker-completion:
  docker-compose:
  dos2unix:
  dtc:
  duf:
  eslint:
  expat:
  eza:
  fd:
  ffmpeg@7:
  ffmpegthumbnailer:
  findutils:
  fish:
  flac:
  flock:
  fnm:
  fontconfig:
  freetds:
  freetype:
  frei0r:
  fribidi:
  fx:
  fzf:
  gawk:
  gdbm:
  gettext:
  gh:
  ghostscript:
  giflib:
  git:
  git-delta:
  gitmoji:
  gitmux:
  glib:
  gmp:
  gnupg:
  gnutls:
  go:
  gpgme:
  gpgmepp:
  granted:
  graphite2:
  grc:
  grep:
  harfbuzz:
  highway:
  htop:
  httpie:
  hyperfine:
  icu4c@76:
  icu4c@77:
  iftop:
  imagemagick:
  imath:
  iproute2mac:
  jansson:
  jaraco.text:
  jasper:
  jbig2dec:
  jpeg-turbo:
  jpeg-xl:
  jq:
  kanata:
  krb5:
  lame:
  lazydocker:
  leptonica:
  libarchive:
  libass:
  libassuan:
  libb2:
  libbluray:
  libde265:
  libdeflate:
  libevent:
  libgcrypt:
  libgit2:
  libgpg-error:
  libheif:
  libidn:
  libidn2:
  libksba:
  liblinear:
  liblqr:
  libmicrohttpd:
  libnghttp2:
  libnghttp3:
  libngtcp2:
  libogg:
  libomp:
  libpng:
  libpq:
  libraw:
  librist:
  libsamplerate:
  libslirp:
  libsndfile:
  libsodium:
  libsoxr:
  libssh:
  libssh2:
  libtasn1:
  libtiff:
  libtool:
  libudfread:
  libunibreak:
  libunistring:
  libusb:
  libuv:
  libvidstab:
  libvmaf:
  libvorbis:
  libvpx:
  libx11:
  libxau:
  libxcb:
  libxdmcp:
  libxext:
  libxrender:
  libyaml:
  libzip:
  lima:
  little-cms2:
  llvm:
  lnav:
  lpeg:
  lua:
  luajit:
  luarocks:
  luv:
  lz4:
  lzo:
  m4:
  mbedtls:
  mercurial:
  moreutils:
  mpdecimal:
  mpfr:
  mpg123:
  msodbcsql17:
  mssql-tools:
  mtr:
  mutagen:
  ncdu:
  ncurses:
  neovim:
  nettle:
  nikto:
  nmap:
  node:
  npth:
  nspr:
  nss:
  nvm:
  oniguruma:
  openapi-generator:
  opencode:
  opencore-amr:
  openexr:
  openjdk:
  openjpeg:
  openjph:
  openssl@1.1:
  openssl@3:
  opentofu:
  openvpn:
  opus:
  oxfmt:
  oxlint:
  p11-kit:
  p7zip:
  pango:
  pcre:
  pcre2:
  peco:
  pinentry:
  pipx:
  pixman:
  pkcs11-helper:
  pkgconf:
  pngpaste:
  pnpm:
  poppler:
  postgresql@13:
  prettierd:
  pwgen:
  pycparser:
  python-argcomplete:
  python-certifi:
  python-cryptography:
  python-markupsafe:
  python-packaging:
  python-typing-extensions:
  python@3.10:
  python@3.11:
  python@3.12:
  python@3.13:
  python@3.14:
  pyyaml:
  qemu:
  rav1e:
  readline:
  reattach-to-user-namespace:
  redis:
  rename:
  ripgrep:
  rtmpdump:
  rubberband:
  ruby:
  rust:
  rustup:
  rustup-init:
  sdl2:
  sesh:
  sevenzip:
  shared-mime-info:
  shellcheck:
  silicon:
  simdjson:
  smartmontools:
  snappy:
  speex:
  sqlite:
  sqls:
  srt:
  ssh-copy-id:
  starship:
  supabase:
  svt-av1:
  swagger-codegen:
  telnet:
  terraform:
  tesseract:
  the_silver_searcher:
  theora:
  tidy-html5:
  tmux:
  tree:
  tree-sitter:
  unbound:
  unibilium:
  unixodbc:
  unp:
  utf8proc:
  uv:
  uvwasi:
  vde:
  vfkit:
  watch:
  webp:
  wget:
  wireguard-go:
  wireguard-tools:
  x264:
  x265:
  xorgproto:
  xvid:
  xz:
  yarn:
  yazi:
  z3:
  zellij:
  zeromq:
  zf:
  zimg:
  zoxide:
  zsh:
  zsh-autocomplete:
  zsh-autosuggestions:
  zsh-completions:
  zsh-syntax-highlighting:
  zsh-vi-mode:
  zstd:
