[aws]
format = 'on [$symbol$profile]($style) '
style = 'bold orange'
symbol = 'ğŸ…°'

[battery]
disabled = true
full_symbol = 'ğŸ”‹'
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
unknown_symbol = ''

[[battery.display]]
threshold = 101
style = "green"

[[battery.display]]
threshold = 25
style = "bold red"

[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "â€¦/"

[package]
disabled = true

[docker_context]
disabled = true

[git_commit]
only_detached = false
disabled = true

[git_metrics]
disabled = true

[git_branch]
disabled = true
[git_status]
disabled = true
